services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: package-management-backend-prod
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=4000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    networks:
      - package-management-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  package-management-network:
    driver: bridge
