name: Continuous Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/Package-Management-System

            # Pull latest code
            git pull origin main

            # Write .env next to docker-compose.prod.yml
            cat > .env <<EOF
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            NODE_ENV=production
            PORT=4000
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
            GOOGLE_AI_API_KEY=${{ secrets.GOOGLE_AI_API_KEY }}
            EOF

            # Optional: quick sanity check (won't print secrets)
            echo "Wrote .env in $(pwd)"
            sed -n '1,3p' .env || true

            # Restart containers
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build

            # Optional cleanup
            docker image prune -f
